export const ROLE_STUDENT = 'ROLE_STUDENT';
export const ROLE_TEACHER = 'ROLE_TEACHER';
export const ROLE_ADMIN = 'ROLE_ADMIN';
export const ROLES = [ROLE_STUDENT, ROLE_TEACHER, ROLE_ADMIN];

export const ROLES_ALLOWED_FOR_LOGIN = [ROLE_STUDENT, ROLE_TEACHER, ROLE_ADMIN];
export const ROLES_ALLOWED_FOR_SELECT = ROLES;
